console.log("Hello, World!");
var myNum = 20;
console.log(myNum);
var myArray = [1,2,3];
console.log(myArray);
var myStack = [];
myStack.push("Balle1");
myStack.push("Balle2");
console.log(myStack);
myStack.pop();
console.log(myStack);
var myQu=[];
myQu.push(1);
myQu.push(2);
myQu.push(3);
myQu.push(4);
console.log(myQu);
console.log(myQu.shift());
myQu.unshift("Hum First,Hum First");
console.log(myQu);
console.log(myQu.splice(1,2));
console.log(myQu);
